-- Theme
require'lualine'.setup {
  options = {
    theme = 'ayu_dark'
  }
}

-- Enable treesitter syntax highlighting
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "arduino",
          "asm",
          "bash",
          "beancount",
          "bibtex",
          "c",
          "c_sharp",
          "cmake",
          "comment",
          "commonlisp",
          "cpp",
          "css",
          "csv",
          "cuda",
          "devicetree",
          "diff",
          "dockerfile",
          "dot",
          "doxygen",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "gnuplot",
          "go",
          "gomod",
          "gosum",
          "gowork",
          "gpg",
          "haskell",
          "haskell_persistent",
          "html",
          "htmldjango",
          "http",
          "ini",
          "java",
          "javascript",
          "jsdoc",
          "json",
          "json5",
          "julia",
          "kotlin",
          "latex",
          "llvm",
          "lua",
          "luadoc",
          "make",
          "markdown",
          "markdown_inline",
          "matlab",
          "meson",
          "nix",
          "objc",
          "objdump",
          "ocaml",
          "org",
          "passwd",
          "perl",
          "php",
          "php_only",
          "phpdoc",
          "pod",
          "printf",
          "properties",
          "prql",
          "psv",
          "purescript",
          "python",
          "regex",
          "ruby",
          "rust",
          "scala",
          "sql",
          "ssh_config",
          "tcl",
          "tmux",
          "toml",
          "typescript",
          "udev",
          "verilog",
          "vim",
          "vimdoc",
          "xcompose",
          "xml",
          "yaml",
          "zathurarc",
        },
  highlight = {
    enable = true,              -- false will disable the whole extension
  },
  rainbow = {
    enable = true,
    colors = require('ayu').rainbow_colors
  },
}

